##model
model_name_or_path: /home/visionnav/code/LLaMA-Factory/models/qwen2-7b-instruct

##method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

##dataset
#dataset: qwen2_sharegpt
#dataset: qwen2_sharegpt, self_identity, self_alpaca, self_c4
dataset: qwen2_sharegpt, self_identity, self_alpaca
template: qwen
cutoff_len: 1024
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16

##output
output_dir: saves/qwen2-7b/lora/sft
logging_steps: 100
save_steps: 100
plot_loss: true
overwrite_output_dir: true

##train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
#learning_rate: 1.0e-5
num_train_epochs: 20
lr_scheduler_type: cosine
#lr_scheduler_type: constant
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

##eval
val_size: 0.3
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100